# Generated by Django 4.1.5 on 2023-02-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fechaCreacion', models.DateField()),
            ],
            options={
                'verbose_name': 'CasoMedicos',
                'verbose_name_plural': 'CasosMedicos',
                'db_table': 'casosmedicos',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diagnostico', models.DateField()),
                ('descripcion', models.TextField()),
                ('aceptado', models.BooleanField()),
                ('fecha_acepta', models.DateField()),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.casomedico')),
            ],
            options={
                'verbose_name': 'Diagnosticos',
                'verbose_name_plural': 'Diagnosticos',
                'db_table': 'diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('RC', 'REGISTRO CIVIL'), ('TI', 'TARJETA IDENTIDAD'), ('CC', 'CEDULA CIUDADANIA'), ('PA', 'PASAPORTE'), ('TE', 'TARJETA_EXTRANJERIA')], default='CC', max_length=50)),
                ('numero_identificacion', models.IntegerField()),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=30)),
                ('lugar_residencia', models.CharField(max_length=30)),
                ('numero_celular', models.CharField(max_length=30)),
                ('numero_registro_profesional', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Medicos',
                'verbose_name_plural': 'Medicos',
                'db_table': 'medicos',
                'ordering': ['apellidos', '-nombres'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('lugar_nacimiento', models.CharField(max_length=30)),
                ('lugar_residencia', models.CharField(max_length=30)),
                ('numero_celular', models.IntegerField(null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('clave', models.CharField(max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Pacientes',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
                'ordering': ['apellidos', '-nombres'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('detalle', models.TextField()),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.diagnostico')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.medico')),
            ],
            options={
                'verbose_name': 'Tratamientos',
                'verbose_name_plural': 'Tratamientos',
                'db_table': 'tratamientos',
            },
        ),
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_soporte', models.DateField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.medico')),
            ],
            options={
                'verbose_name': 'Soportes',
                'verbose_name_plural': 'Soportes',
                'db_table': 'soportes',
            },
        ),
        migrations.CreateModel(
            name='ImagenDiagnostica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dermobkend.casomedico')),
            ],
            options={
                'verbose_name': 'ImagenDiagnostica',
                'verbose_name_plural': 'ImagenesDianosticas',
                'db_table': 'imagenesdianosticas',
            },
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.medico'),
        ),
        migrations.AddField(
            model_name='casomedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.medico'),
        ),
        migrations.AddField(
            model_name='casomedico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.paciente'),
        ),
    ]
