# Generated by Django 4.1.5 on 2023-03-11 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagendiagnostica',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='dermobkend.casomedico'),
        ),
    ]
