# Generated by Django 4.1.5 on 2023-02-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casomedico',
            old_name='fechaCreacion',
            new_name='fecha_creacion',
        ),
    ]
