# Generated by Django 4.1.5 on 2023-02-02 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0002_rename_fechacreacion_casomedico_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casomedico',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
