# Generated by Django 4.1.5 on 2023-02-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0003_alter_casomedico_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casomedico',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dermobkend.medico'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
