# Generated by Django 4.1.5 on 2023-02-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0004_soporte_fecha_grado_soporte_graduado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='url',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
