# Generated by Django 4.1.5 on 2023-02-02 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0004_alter_casomedico_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casomedico',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dermobkend.paciente'),
        ),
    ]
