# Generated by Django 4.1.5 on 2023-02-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0005_soporte_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='tipo_soporte',
            field=models.CharField(choices=[('PREGRADO', 'PREGRADO'), ('ESPECIALIZACION', 'ESPECIALIZACION'), ('CERTIFICACION', 'CERTIFICACION'), ('SEMINARIO', 'SEMINARIO'), ('DIPLOMADO', 'DIPLOMADO')], default='PREGRADO', max_length=50),
        ),
    ]
