# Generated by Django 4.1.5 on 2023-02-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0006_especialidad_medico_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casomedico',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
