# Generated by Django 4.1.5 on 2023-02-19 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0006_soporte_tipo_soporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='perfil_dermatologico',
            field=models.CharField(choices=[('FOTOTIPO I', 'Personas que tienen un color de pelo rubio o pelirrojo, ojos claros, ya sean verdes o azules, y una piel muy pálida o blanca. Suelen quemarse con mucha facilidad durante sus exposiciones al sol y, por ello, son los que más cuidados precisan tomar y quienes deben usar los bloqueador solares con la máxima protección'), ('FOTOTIPO II', 'Personas que tienen un color de pelo rubio o pelirrojo, ojos claros, ya sean verdes o azules, y una piel muy pálida o blanca. Suelen quemarse con mucha facilidad durante sus exposiciones al sol y, por ello, son los que más cuidados precisan tomar y quienes deben usar los bloqueador solares con la máxima protección'), ('FOTOTIPO III', 'Personas que tienen un color de pelo rubio o pelirrojo, ojos claros, ya sean verdes o azules, y una piel muy pálida o blanca. Suelen quemarse con mucha facilidad durante sus exposiciones al sol y, por ello, son los que más cuidados precisan tomar y quienes deben usar los bloqueador solares con la máxima protección'), ('FOTOTIPO IV', 'Se trata de personas con pelo castaño oscuro, los ojos marrones y la piel, de por sí, morena. No suelen tener problemas para broncearse, y su piel adopta una tonalidad dorada con facilidad. Sólo se queman si están mucho tiempo tomando el sol, pero eso no significa que no tengan que usar protector solar, con una protección normal'), ('FOTOTIPO V', 'Son personas que tienen la piel oscura, al igual que los ojos, el pelo color negro. Se broncean con muchísima facilidad y no es necesario que se expongan mucho al sol para estar morenos. Es muy raro que se quemen, y esto sólo ocurre cuando están expuestos a las radiaciones solares de una manera excesiva. Sin embargo, ellos también necesitan usar protección solar'), ('FOTOTIPO VI', 'personas de raza negra. Sus pieles son muy oscuras, al igual que su cabello y ojos. Es casi imposible que se quemen, pues tienen una piel muy pigmentada, aunque deben evitar la exposición al sol sin protección, pues las radiaciones, aunque no les produzcan daños externos, también son nocivas')], default='FOTOTIPO IV', max_length=255),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='institucion_educativa',
            field=models.TextField(default='NINGUNA', max_length=150),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soportes_medico', to='dermobkend.medico'),
        ),
    ]
