# Generated by Django 4.1.5 on 2023-02-19 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0007_paciente_perfil_dermatologico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(max_length=200, null=True)),
                ('forma', models.TextField(max_length=200, null=True)),
                ('numero', models.TextField(max_length=200, null=True)),
                ('distribucion', models.TextField(max_length=200, null=True)),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dermobkend.casomedico')),
            ],
            options={
                'verbose_name': 'Lesion',
                'verbose_name_plural': 'Lesion',
                'db_table': 'Lesion',
            },
        ),
    ]
