# Generated by Django 4.1.5 on 2023-02-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0007_alter_casomedico_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casomedico',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
