# Generated by Django 4.1.5 on 2023-02-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0008_alter_casomedico_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='casomedico',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('ENREVISION', 'Reservado'), ('SELECCIONADO', 'Seleccionado'), ('LIBRE', 'Libre')], max_length=50, null=True),
        ),
    ]
