# Generated by Django 4.1.5 on 2023-02-19 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0008_lesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesion',
            name='caso',
        ),
        migrations.AddField(
            model_name='casomedico',
            name='lesion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesiones_caso', to='dermobkend.lesion'),
        ),
    ]
