# Generated by Django 4.1.5 on 2023-02-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0009_casomedico_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casomedico',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casomedico',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('ENREVISION', 'Reservado'), ('SELECCIONADO', 'Seleccionado'), ('LIBRE', 'Libre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='casomedico',
            name='fecha_creacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='casomedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.medico'),
        ),
        migrations.AlterField(
            model_name='casomedico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.paciente'),
        ),
    ]
