# Generated by Django 4.1.5 on 2023-02-03 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0010_alter_casomedico_descripcion_alter_casomedico_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casomedico',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dermobkend.medico'),
        ),
    ]
