# Generated by Django 4.1.5 on 2023-02-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0011_alter_casomedico_medico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casomedico',
            options={},
        ),
        migrations.AlterField(
            model_name='casomedico',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos_medicos', to='dermobkend.medico'),
        ),
        migrations.AlterField(
            model_name='casomedico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_medicos', to='dermobkend.paciente'),
        ),
    ]
