# Generated by Django 4.1.5 on 2023-02-04 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0012_alter_casomedico_options_alter_casomedico_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casomedico',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos_medicos_medico', to='dermobkend.medico'),
        ),
        migrations.AlterField(
            model_name='casomedico',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos_medicos', to='dermobkend.paciente'),
        ),
    ]
