# Generated by Django 4.1.5 on 2023-01-25 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diagnostico', models.DateField()),
                ('descripcion', models.TextField()),
                ('aceptado', models.BooleanField()),
                ('fecha_acepta', models.DateField()),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.casomedico')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('lugarNacimiento', models.CharField(max_length=30)),
                ('lugarResidencia', models.CharField(max_length=30)),
                ('numeroCelular', models.IntegerField()),
                ('numeroRegistroProfesional', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.TextField()),
                ('lugar_residencia', models.TextField()),
                ('numero_celular', models.IntegerField()),
                ('correo', models.TextField()),
                ('clave', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('detalle', models.TextField()),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.diagnostico')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.medico')),
            ],
        ),
        migrations.CreateModel(
            name='SoporteProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_soporte', models.DateField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.medico')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenDiagnostica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.casomedico')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.medico'),
        ),
        migrations.AddField(
            model_name='casomedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.medico'),
        ),
        migrations.AddField(
            model_name='casomedico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dermobkend.paciente'),
        ),
    ]
