# Generated by Django 4.1.5 on 2023-01-25 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0002_alter_medico_options_alter_imagendiagnostica_caso_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medico',
            table='medico',
        ),
    ]
