# Generated by Django 4.1.5 on 2023-01-25 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0003_alter_medico_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={},
        ),
        migrations.AlterModelTable(
            name='medico',
            table=None,
        ),
    ]
