# Generated by Django 4.1.5 on 2023-01-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0004_alter_medico_options_alter_medico_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['apellidos', '-nombres'], 'verbose_name': 'Medico', 'verbose_name_plural': 'Medicos'},
        ),
        migrations.AlterModelTable(
            name='medico',
            table='medico',
        ),
    ]
