# Generated by Django 4.1.5 on 2023-01-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0005_alter_medico_options_alter_medico_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoporteProfesional',
            new_name='Soporte',
        ),
        migrations.AlterModelOptions(
            name='casomedico',
            options={'verbose_name': 'CasoMedico', 'verbose_name_plural': 'CasosMedicos'},
        ),
        migrations.AlterModelOptions(
            name='diagnostico',
            options={'verbose_name': 'Diagnostico', 'verbose_name_plural': 'Diagnosticos'},
        ),
        migrations.AlterModelOptions(
            name='imagendiagnostica',
            options={'verbose_name': 'ImagenDiagnostica', 'verbose_name_plural': 'ImagenesDianosticas'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['apellidos', '-nombres'], 'verbose_name': 'Medicos', 'verbose_name_plural': 'Medicos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['apellidos', '-nombres'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='soporte',
            options={'verbose_name': 'Soportes', 'verbose_name_plural': 'Soportes'},
        ),
        migrations.AlterModelOptions(
            name='tratamiento',
            options={'verbose_name': 'Tratamientos', 'verbose_name_plural': 'Tratamientos'},
        ),
        migrations.AlterModelTable(
            name='casomedico',
            table='casosmedicos',
        ),
        migrations.AlterModelTable(
            name='diagnostico',
            table='diagnosticos',
        ),
        migrations.AlterModelTable(
            name='imagendiagnostica',
            table='imagenesdianosticas',
        ),
        migrations.AlterModelTable(
            name='medico',
            table='medicos',
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='pacientes',
        ),
        migrations.AlterModelTable(
            name='soporte',
            table='soportes',
        ),
        migrations.AlterModelTable(
            name='tratamiento',
            table='tratamientos',
        ),
    ]
