# Generated by Django 4.1.5 on 2023-01-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0006_rename_soporteprofesional_soporte_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casomedico',
            options={'verbose_name': 'CasoMedicos', 'verbose_name_plural': 'CasosMedicos'},
        ),
        migrations.AlterModelOptions(
            name='diagnostico',
            options={'verbose_name': 'Diagnosticos', 'verbose_name_plural': 'Diagnosticos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['apellidos', '-nombres'], 'verbose_name': 'Pacientes', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_nacimiento',
            new_name='fechaNacimiento',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='numero_celular',
            new_name='numeroCelular',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='lugar_nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='lugar_residencia',
        ),
        migrations.AddField(
            model_name='paciente',
            name='lugarNacimiento',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='lugarResidencia',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombres',
            field=models.CharField(max_length=50),
        ),
    ]
