# Generated by Django 4.1.5 on 2023-01-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermobkend', '0008_alter_paciente_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='clave',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numeroCelular',
            field=models.IntegerField(null=True),
        ),
    ]
